
client1:
  lr: 0.01
  # lr: 0.001
  bs: 64
  ep: 500
  task: cls
  model: gin
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 8
  task: C


client2:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  task: cls
  model: gcn
  in_dim: 20
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 4
  task: C

client3:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  task: cls
  model: gcn
  in_dim: 37
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 0
  task: C

client4:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  task: cls
  model: gcn
  in_dim: 7
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 4
  task: C

client5:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  task: cls
  model: gcn
  in_dim: 18
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 4
  task: C

client6:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 8
  task: C

client7:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 38
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 0
  task: C

client8:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 19
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  dim_edge: 4
  task: C

client9:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 28
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  dim_edge: 3
  task: R

client10:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 6
  in_channel: 64
  out_channel: 64
  num_cls: 10
  max_depth: 2
  dim_edge: 4
  task: R

client11:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  dim_edge: 8
  task: R

client12:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  dim_edge: 8
  task: R

client13:
  # lr: 0.001
  lr: 0.01
  bs: 64
  ep: 500
  in_dim: 11
  in_channel: 64
  out_channel: 64
  num_cls: 12
  max_depth: 2
  dim_edge: 4
  task: R

data_sp:
  shuffle: True
  root_path: data/splitFold/data/
  fold: 1
  batch_size: 4096
  num_worker: 4

server:
  round: 50

exp:
  path: data/exp/

device: cuda:0