client1:
  lr: 0.001
  bs: 64
  ep: 5
  task: cls
  model: gin
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 8
  dropout: 0.2
  task: C


client2:
  lr: 0.001
  bs: 64
  ep: 5
  task: cls
  model: gcn
  in_dim: 20
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 0
  dropout: 0.5
  task: C

client3:
  lr: 0.001
  bs: 64
  ep: 5
  task: cls
  model: gcn
  in_dim: 37
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 0
  dropout: 0.2
  task: C

client4:
  lr: 0.001
  bs: 64
  ep: 5
  task: cls
  model: gcn
  in_dim: 7
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 4
  dropout: 0.2
  task: C

client5:
  lr: 0.001
  bs: 64
  ep: 5
  task: cls
  model: gcn
  in_dim: 18
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 4
  dropout: 0.2
  task: C

client6:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 8
  dropout: 0.2
  task: C

client7:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 38
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 0
  dropout: 0.2
  task: C

client8:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 19
  in_channel: 64
  out_channel: 64
  num_cls: 2
  max_depth: 2
  edge_dim: 4
  dropout: 0.2
  task: C

client9:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 28
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  edge_dim: 3
  dropout: 0.2
  task: R

client10:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 6
  in_channel: 64
  out_channel: 64
  num_cls: 10
  max_depth: 2
  edge_dim: 4
  dropout: 0.2
  task: R

# 在circle中只使用 0.005和0.003
client11:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  edge_dim: 8
  dropout: 0.2
  task: R

client12:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 22
  in_channel: 64
  out_channel: 64
  num_cls: 1
  max_depth: 2
  edge_dim: 8
  dropout: 0.2
  task: R

client13:
  lr: 0.001
  bs: 64
  ep: 5
  in_dim: 11
  in_channel: 64
  out_channel: 64
  num_cls: 12
  max_depth: 2
  edge_dim: 4
  dropout: 0.2
  task: R

data_sp:
  shuffle: True
  root_path: /home/featurize/data/cikm2022
  batch_size: 4096
  num_worker: 4

server:
  round: 500

exp:
  path: /home/featurize/cikm22/exp

device: cuda:0